version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
    environment:
      NODE_ENV: dev
      MONGO_URI: mongodb://admin:admin@mongo:27017/admin?authSource=admin
      JWT_ACCESS_SECRET: 123456ab
      JWT_REFRESH_SECRET: 123456ab
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo

  mongo:
    ports:
      - '27017:27017'
    container_name: mongo
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    image: mongo
